# Keyboard name
CONFIG_ZMK_KEYBOARD_NAME="백합58"

# Enable Bluetooth support
CONFIG_ZMK_BLE=y

# Enable encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Enable mouse emulation
CONFIG_ZMK_POINTING=y

# Enable TPS43 trackpad
CONFIG_ZMK_MOUSE=y
CONFIG_INPUT=y
CONFIG_INPUT_AZOTEQ_IQS5XX=yONFIG_INPUT_AZOTEQ_IQS5XX=y

# Enable OLED Display
#CONFIG_ZMK_DISPLAY=y
