name: Build ZMK firmware

on:
  push:
    branches: [ "lily58" ]
  pull_request:
    branches: [ "lily58" ]
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3.0
